import Link from 'next/link';

interface CaseTraceItem {
  id: string;
  projectTitle: string;
  projectHref: string;
  badge: string;
  question: string;
  hypothesis: string;
  prototype: string;
  system: string;
  evaluation: string;
  invariant: string;
}

const caseTraces: CaseTraceItem[] = [
  {
    id: 'hybrid-rag-trace',
    projectTitle: 'Enterprise Knowledge Assistant (Hybrid RAG)',
    projectHref: '/work#hybrid-rag',
    badge: 'AI_SYSTEM',
    question:
      'Why does standard dense vector cosine search consistently miss exact alphanumeric part codes, section numbers, and tabular data in complex manuals?',
    hypothesis:
      'Combining sparse lexical retrieval (BM25) with dense vector embeddings via non-parametric Reciprocal Rank Fusion (RRF) guarantees exact lexical coordinates without sacrificing conceptual semantic search.',
    prototype:
      'Isolated Python rank-blending script benchmarked across 50 technical PDF manuals with complex engineering specifications.',
    system:
      'Production FastAPI + LlamaIndex + ChromaDB runtime with PyMuPDF OCR fallback and an MD5 hash query caching layer.',
    evaluation:
      'Cross-encoder reranking caused 1.2s+ latency spikes on unbounded chunk candidate sets. Bounded rerank pool to top-25 chunks to guarantee sub-400ms end-to-end response budgets.',
    invariant:
      'Score normalization across heterogeneous sparse and dense scores causes calibration drift. Rank-based fusion (RRF) is mathematically invariant to score scaling.',
  },
  {
    id: 'agentforge-trace',
    projectTitle: 'AgentForge Reliability Harness',
    projectHref: '/work#agentforge',
    badge: 'AI_RELIABILITY_EVALUATION',
    question:
      'Why do autonomous multi-turn tool agents fail catastrophically during transient network failures, duplicate retries, or rate limits?',
    hypothesis:
      'Subjecting agent runtimes to deterministic synthetic chaos (HTTP 429, payload corruption, socket timeouts) inside isolated Docker containers will prove tool idempotency and recovery state transitions.',
    prototype:
      'Lightweight mock tool environment simulating adversarial API conditions and checking for duplicate database mutations.',
    system:
      'Automated containerized testing suite with structured regression traces and reproducible chaos test runs.',
    evaluation:
      'Fuzzy string matching on LLM outputs produced false positives during evaluation. Replaced fuzzy text matching with strict pre- and post-tool state delta verification.',
    invariant:
      'Never assert on conversational text generated by an agent. Verify only observable external state mutations and idempotent tool call logs.',
  },
  {
    id: 'daily-sahayak-trace',
    projectTitle: 'Daily Sahayak',
    projectHref: '/work#daily-sahayak',
    badge: 'PRODUCT',
    question:
      'Why do users inevitably abandon mathematically optimal time-blocking apps when daily commitments overflow?',
    hypothesis:
      'Rigid schedules create decision friction and guilt. An adaptive state machine that recalculates downstream slack dynamically preserves momentum over compliance.',
    prototype:
      'Interactive fluid schedule engine capable of sliding downstream blocks without user confirmation modals.',
    system:
      'Fullstack Next.js/TypeScript application integrating multi-factor priority scoring and automated calendar conflict resolution.',
    evaluation:
      'Complex multi-variable optimization algorithms created unpredictable schedule shifts. Simplified the scoring formulation to 3 transparent pillars: Urgency, Cognitive Load, and Deadlines.',
    invariant:
      'Friction reduction and user momentum strictly supersede mathematical timetabling optimality in human productivity tools.',
  },
];

export function CaseTraces() {
  return (
    <section className="relative py-16 px-6 md:px-12 lg:px-20 max-w-[1400px] mx-auto border-t border-[#38BDF8]/20">
      {/* Section Header */}
      <div className="pb-8 border-b border-[#38BDF8]/15 mb-12">
        <div className="font-mono text-xs text-[#38BDF8] uppercase tracking-[0.2em] mb-2">
          SECTION 05 // SYSTEM TRANSFORMATION TRACES
        </div>
        <h2 className="font-mono text-2xl sm:text-4xl font-bold text-white uppercase tracking-tight">
          From Question ➔ <span className="text-[#38BDF8]">Resilient Architecture</span>.
        </h2>
        <p className="mt-4 text-neutral-400 font-sans text-base max-w-2xl leading-relaxed">
          How real portfolio projects navigated the build loop: starting with an empirical question, encountering
          production failure, and extracting permanent architectural invariants.
        </p>
      </div>

      {/* Case Traces Stack */}
      <div className="space-y-12">
        {caseTraces.map((trace) => (
          <div
            key={trace.id}
            className="p-6 md:p-10 rounded-2xl bg-[#081522] border border-[#38BDF8]/25 shadow-xl font-mono text-xs space-y-8"
          >
            {/* Header & Link */}
            <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-[#38BDF8]/20">
              <div className="flex items-center gap-3">
                <span className="px-2.5 py-0.5 rounded bg-[#38BDF8]/20 text-[#38BDF8] font-bold">
                  {trace.badge}
                </span>
                <h3 className="text-white text-base md:text-lg font-bold">{trace.projectTitle}</h3>
              </div>

              <Link
                href={trace.projectHref}
                className="text-[#38BDF8] hover:text-white font-bold transition-colors inline-flex items-center gap-1"
              >
                <span>VIEW CASE IN ARCHIVE</span>
                <span>→</span>
              </Link>
            </div>

            {/* Stepped Pipeline Progression */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
              {/* Step 1: Question */}
              <div className="p-4 rounded bg-[#06101B] border border-white/5 space-y-2">
                <span className="text-[#7DD3FC]/70 text-[10px] font-bold uppercase tracking-wider block">
                  01 // THE QUESTION
                </span>
                <p className="font-sans text-neutral-200 text-xs leading-relaxed">{trace.question}</p>
              </div>

              {/* Step 2: Hypothesis */}
              <div className="p-4 rounded bg-[#06101B] border border-white/5 space-y-2">
                <span className="text-[#7DD3FC]/70 text-[10px] font-bold uppercase tracking-wider block">
                  02 // HYPOTHESIS
                </span>
                <p className="font-sans text-neutral-200 text-xs leading-relaxed">{trace.hypothesis}</p>
              </div>

              {/* Step 3: Prototype */}
              <div className="p-4 rounded bg-[#06101B] border border-white/5 space-y-2">
                <span className="text-[#7DD3FC]/70 text-[10px] font-bold uppercase tracking-wider block">
                  03 // VERIFIABLE SPIKE
                </span>
                <p className="font-sans text-neutral-200 text-xs leading-relaxed">{trace.prototype}</p>
              </div>

              {/* Step 4: System Architecture */}
              <div className="p-4 rounded bg-[#06101B] border border-[#38BDF8]/20 space-y-2">
                <span className="text-[#38BDF8] text-[10px] font-bold uppercase tracking-wider block">
                  04 // HARDENED SYSTEM
                </span>
                <p className="font-sans text-neutral-200 text-xs leading-relaxed">{trace.system}</p>
              </div>

              {/* Step 5: Evaluation & Failure */}
              <div className="p-4 rounded bg-red-950/20 border border-red-500/30 space-y-2">
                <span className="text-red-400 text-[10px] font-bold uppercase tracking-wider block">
                  05 // EVALUATION &amp; REGRESSION
                </span>
                <p className="font-sans text-neutral-300 text-xs leading-relaxed">{trace.evaluation}</p>
              </div>

              {/* Step 6: Permanent Invariant */}
              <div className="p-4 rounded bg-emerald-950/20 border border-emerald-500/30 space-y-2">
                <span className="text-emerald-400 text-[10px] font-bold uppercase tracking-wider block">
                  06 // ARCHITECTURAL INVARIANT
                </span>
                <p className="font-sans text-emerald-200 text-xs leading-relaxed">{trace.invariant}</p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
